### PR TITLE
use config file

### PR DESCRIPTION
**Pull request by noahdietz**
Addresses #28 
- change `shipyardctl get token` to `shipyardctl login` 
- write credentials (username and auth token) to config file `~/.shipyardctl/config` (instead of dumping to `stdout`)
- read auth token from in this order: cli flag, environment, config file

### CODE REVIEW

**Comment by noahdietz** [comment]
Would like to make multiple contexts work, still need to design its usage

**Comment by whitlockjc** [comment]
For different contexts, you could just store username+host and that could be a composite key.

**Comment by noahdietz** [comment]
@whitlockjc what should a context even include? I'm a little unsure of it's scope now...
`cluster_target` `sso-login-url` `token` `org` `env`, a `name`? The token has to be refreshed and saving usr/pswd to file is insecure, so i'm not sure if it is THAT useful to keep one in there.

**Comment by whitlockjc** [comment]
Off the top of my head, this is an idea.  We could have a server/target context that would be analogous to Kubernetes' `cluster`:
- `cluster_target`
- `name`
- `sso_login_url`

We would then have a `user` context that would be the token, probably with a name to identify it.  This would be analogous to Kubernetes' `user`.  Finally, we could have a named `context` that would allow you to give a name to a server/target+user.

If we followed this model, it would be identical to Kubernetes.  Thoughts?

**Comment by noahdietz** [comment]
Sounds good to me! Ill get cranking on it

**Comment by noahdietz** [comment]
This PR is now also addressing #6 , but following the design spelled out here

**Pull request merged**
